global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'wago'
    static_configs:
      - targets: ['modbus_exporter:9100']

  - job_name: 'temperature-sensors'
    static_configs:
      - targets: ['iot-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'heatpump'
    static_configs:
      - targets: ['lg_r290_service:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

